package io.thingshub.transport.throttler;

public enum ResourceType {
	TOTAL_CONNECTIONS, //
	TOTAL_SESSION_MEMORY_BYTES, //
	TOTAL_PERSISTENT_SESSIONS, //
	TOTAL_PERSISTENT_SESSION_SPACE_BYTES, //
	TOTAL_SHARED_SUBSCRIPTIONS, //
	TOTAL_TRANSIENT_SUBSCRIPTIONS, //
	TOTAL_PERSISTENT_SUBSCRIPTIONS, //
	TOTAL_RETAIN_MESSAGE_SPACE_BYTES, //
	TOTAL_RETAIN_TOPICS, //
	TOTAL_CONNECT_PER_SECOND, //
	TOTAL_INBOUND_BYTES_PER_SECOND, //
	TOTAL_TRANSIENT_SUBSCRIBE_PER_SECOND, //
	TOTAL_PERSISTENT_SUBSCRIBE_PER_SECOND, //
	TOTAL_TRANSIENT_UNSUBSCRIBE_PER_SECOND, //
	TOTAL_PERSISTENT_UNSUBSCRIBE_PER_SECOND, //
	TOTAL_TRANSIENT_FANOUT_BYTES_PER_SECONDS, //
	TOTAL_PERSISTENT_FANOUT_BYTES_PER_SECONDS, //
	TOTAL_RETAINED_MESSAGES_PER_SECONDS, //
	TOTAL_RETAINED_BYTES_PER_SECOND, //
	TOTAL_RETAIN_MATCH_PER_SECONDS, //
	TOTAL_RETAIN_MATCH_BYTES_PER_SECOND,
}